"""marketplace, agent policy, persistent tasks, demo-data scoping

Adds the controlled simulated marketplace (merchants, products, listings,
carts, orders), the user agent policy, persistent agent tasks, and the
columns that let /demo/reset delete only demo data (users.is_demo,
agents.owner_user_id, audit_logs.user_id). Catalogue rows are seeded by
app.services.catalog_seed (idempotent upsert at startup), not here.

Revision ID: 0004_marketplace
Revises: 0003_enum_labels
Create Date: 2026-09-27 04:10:51.807867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0004_marketplace'
down_revision = '0003_enum_labels'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('tagline', sa.String(length=160), nullable=True),
    sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('free_delivery_above', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('delivery_minutes', sa.Integer(), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('brand', sa.String(length=60), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('subcategory', sa.String(length=32), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_table('agent_policies',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('overall_authority', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('per_transaction_limit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('allowed_categories', sa.JSON(), nullable=False),
    sa.Column('allowed_merchants', sa.JSON(), nullable=False),
    sa.Column('approval_mode', sa.String(length=24), nullable=False),
    sa.Column('approval_threshold', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('mandate_id', sa.UUID(), nullable=True),
    sa.Column('root_capability_id', sa.UUID(), nullable=True),
    sa.Column('main_agent_id', sa.UUID(), nullable=True),
    sa.Column('search_agent_id', sa.UUID(), nullable=True),
    sa.Column('search_capability_id', sa.UUID(), nullable=True),
    sa.Column('negotiation_agent_id', sa.UUID(), nullable=True),
    sa.Column('negotiation_capability_id', sa.UUID(), nullable=True),
    sa.Column('purchase_agent_id', sa.UUID(), nullable=True),
    sa.Column('wallet_agent_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('agent_tasks',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('instruction', sa.String(length=200), nullable=False),
    sa.Column('budget', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('cart_id', sa.UUID(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('refs', sa.JSON(), nullable=False),
    sa.Column('authorization', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('simulation', sa.JSON(), nullable=True),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_tasks_status'), 'agent_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_agent_tasks_user_id'), 'agent_tasks', ['user_id'], unique=False)
    op.create_table('carts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('merchant_id', sa.String(length=32), nullable=True),
    sa.Column('selection_mode', sa.String(length=8), nullable=True),
    sa.Column('selection_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carts_task_id'), 'carts', ['task_id'], unique=False)
    op.create_index(op.f('ix_carts_user_id'), 'carts', ['user_id'], unique=False)
    op.create_table('merchant_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.CheckConstraint('price > 0', name='ck_listing_price_positive'),
    sa.CheckConstraint('stock >= 0', name='ck_listing_stock_nonnegative'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'product_id', name='uq_listing_merchant_product')
    )
    op.create_index(op.f('ix_merchant_listings_merchant_id'), 'merchant_listings', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_merchant_listings_product_id'), 'merchant_listings', ['product_id'], unique=False)
    op.create_table('cart_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity > 0 AND quantity <= 50', name='ck_cart_item_quantity'),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cart_id', 'product_id', name='uq_cart_product')
    )
    op.create_index(op.f('ix_cart_items_cart_id'), 'cart_items', ['cart_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.String(length=16), nullable=True),
    sa.Column('merchant_id', sa.String(length=32), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('delivery_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('reservation_id', sa.UUID(), nullable=False),
    sa.Column('capability_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('approval', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('total = subtotal + delivery_fee', name='ck_order_total'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number'),
    sa.UniqueConstraint('payment_id')
    )
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('product_name', sa.String(length=120), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.add_column('agents', sa.Column('owner_user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_agents_owner_user_id'), 'agents', ['owner_user_id'], unique=False)
    op.create_foreign_key('fk_agents_owner_user_id', 'agents', 'users', ['owner_user_id'], ['id'])
    op.add_column('audit_logs', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_foreign_key('fk_audit_logs_user_id', 'audit_logs', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('is_demo', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_demo')
    op.drop_constraint('fk_audit_logs_user_id', 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'user_id')
    op.drop_constraint('fk_agents_owner_user_id', 'agents', type_='foreignkey')
    op.drop_index(op.f('ix_agents_owner_user_id'), table_name='agents')
    op.drop_column('agents', 'owner_user_id')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_cart_items_cart_id'), table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index(op.f('ix_merchant_listings_product_id'), table_name='merchant_listings')
    op.drop_index(op.f('ix_merchant_listings_merchant_id'), table_name='merchant_listings')
    op.drop_table('merchant_listings')
    op.drop_index(op.f('ix_carts_user_id'), table_name='carts')
    op.drop_index(op.f('ix_carts_task_id'), table_name='carts')
    op.drop_table('carts')
    op.drop_index(op.f('ix_agent_tasks_user_id'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_status'), table_name='agent_tasks')
    op.drop_table('agent_tasks')
    op.drop_table('agent_policies')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    op.drop_table('merchants')
    # ### end Alembic commands ###
