"""day6_grant_signature

Revision ID: 184744da11ad
Revises: 2b154399fdfd
Create Date: 2026-09-24 15:17:09.866679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '184744da11ad'
down_revision = '2b154399fdfd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capabilities', sa.Column('grant_signature', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('capabilities', 'grant_signature')
    # ### end Alembic commands ###
