"""day6_payment_utr_reference

Revision ID: 2b154399fdfd
Revises: 68eeaf517e4e
Create Date: 2026-09-24 15:08:23.927679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b154399fdfd'
down_revision = '68eeaf517e4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('utr_reference', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'utr_reference')
    # ### end Alembic commands ###
