"""day6_pubkey_nonce

Revision ID: 68eeaf517e4e
Revises: 0002
Create Date: 2026-09-24 14:50:40.652352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68eeaf517e4e'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_nonces',
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.String(length=64), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index(op.f('ix_request_nonces_agent_id'), 'request_nonces', ['agent_id'], unique=False)
    op.add_column('agents', sa.Column('public_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'public_key')
    op.drop_index(op.f('ix_request_nonces_agent_id'), table_name='request_nonces')
    op.drop_table('request_nonces')
    # ### end Alembic commands ###
